### ISSUE TITLE
How can I get the data in the origin data folder？

### ISSUE THREAD

**Issue by jhxqy** [hyllios/CGAT#2]
I want to train the model, how to get the content in the origin_data folder? How does the data flow? Is origin_data processed through add_volume, then prepare, and then train?

**Comment by jhxqy** [comment]
@hyllios @JonathanSchmidt1 @noah-hoffmann

**Comment by JonathanSchmidt1** [comment]
I originally answered your email but I will just add the answer with some additional information here in case anyone else has the same question:

the prepare_data scripts generally takes  a file containing a lists of ComputedStructureEntries or a source directory containing a list of such files as input. If you want to use another format just change it in the CompositionDataPrepare class. It will output data ready for training containing the neighborlist of the graphs, the composition, target data and some extra information. the folders in the train.sh script are in case you want to select your train/val/test data outside the lightningmodule. You can also use a single input file or directory, than the  separation into different sets  will be performed automatically before training.

On the materials cloud you can find code to create ComputedStructureEntries for our calculations that you can load with the code in the README. For the aflow and matpro data you would have to download the compounds with the respective ids and then make sure that all data uses the consistent energy correction of the materials project (we used the old ones).
